[package]
name = "cambi_pool"
version = "0.1.0"
description = "cambI: casa de câmbio on-chain em que quem deposita ganha com as trocas"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "cambi_pool"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
