[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
cambi_pool = "AgZtr464VxDFXuYnr3THUUa8Ww1jxBWJXEKQJEQc35XJ"

[programs.localnet]
cambi_pool = "AgZtr464VxDFXuYnr3THUUa8Ww1jxBWJXEKQJEQc35XJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
# Implanta como programa atualizável: o initialize exige a autoridade de upgrade.
upgradeable = true

[scripts]
test = "npm run test:anchor"
